# except for the badge creation, keep icar-main-commit.yml jobs in parity
name: HICAR Pull Request Actions
on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build_and_test_HICAR:
    runs-on: ubuntu-latest
    # make sure these permissions are set so that
    # VS Code can connect to the machine
    permissions:
      actions: read
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@master

      # Build Dependencies then HICAR
      - name: Dependencies
        run: bash .github/scripts/hicar_install_utils.sh hicar_dependencies
      - name: Build
        run: bash .github/scripts/hicar_install_utils.sh hicar_install

      # Run HICAR with generated test data
      - name: Generate Test Run Data
        run: bash .github/scripts/hicar_install_utils.sh gen_test_run_data
      - name: Execute Test Run
        run: bash .github/scripts/hicar_install_utils.sh execute_test_run
      - name: Debug Build
        uses: stateful/vscode-server-action@v1
        if: failure()
        with:
          timeout: '300000'       # optional, default: 30000
